// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using weddingplannerBES.Models;

namespace weddingplannerBES.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20190624204845_SecondMigration")]
    partial class SecondMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("weddingplannerBES.Models.Reservation", b =>
                {
                    b.Property<int>("RSVPId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GuestId");

                    b.Property<int>("OneWeddingId");

                    b.HasKey("RSVPId");

                    b.HasIndex("GuestId");

                    b.HasIndex("OneWeddingId");

                    b.ToTable("ReservationsTable");
                });

            modelBuilder.Entity("weddingplannerBES.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("UserId");

                    b.ToTable("UsersTable");
                });

            modelBuilder.Entity("weddingplannerBES.Models.Wedding", b =>
                {
                    b.Property<int>("WeddingId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CreatorId");

                    b.Property<DateTime>("Date");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("WedderOneBride")
                        .IsRequired();

                    b.Property<string>("WedderTwoGroom")
                        .IsRequired();

                    b.HasKey("WeddingId");

                    b.HasIndex("CreatorId");

                    b.ToTable("WeddingsTable");
                });

            modelBuilder.Entity("weddingplannerBES.Models.Reservation", b =>
                {
                    b.HasOne("weddingplannerBES.Models.User", "Guest")
                        .WithMany("Weddings")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("weddingplannerBES.Models.Wedding", "OneWedding")
                        .WithMany("Guests")
                        .HasForeignKey("OneWeddingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("weddingplannerBES.Models.Wedding", b =>
                {
                    b.HasOne("weddingplannerBES.Models.User", "Creator")
                        .WithMany("PlannedWeddingsbyCreator")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
